# -*- coding: utf-8 -*-
"""Matchcase assignmnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBDjh7mm0PpptW8Jv_Bs8g7ILrDevZST

1. Display Month Names (1–12)
"""

month = int(input("Enter month number: "))

match month:
    case 1:
        print("January")
    case 2:
        print("February")
    case 3:
        print("March")
    case 4:
        print("April")
    case 5:
        print("May")
    case 6:
        print("June")
    case 7:
        print("July")
    case 8:
        print("August")
    case 9:
        print("September")
    case 10:
        print("October")
    case 11:
        print("November")
    case 12:
        print("December")
    case _:
        print("Invalid Month")

"""2. Calculator"""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
op = input("Enter operator (+,-,*,/): ")

match op:
    case "+":
        print(num1 + num2)
    case "-":
        print(num1 - num2)
    case "*":
        print(num1 * num2)
    case "/":
        print(num1 / num2)
    case _:
        print("Invalid Operator")

"""3. Check Vowel or Consonant"""

ch = input("Enter a letter: ")

match ch.lower():
    case "a" | "e" | "i" | "o" | "u":
        print("Vowel")
    case _:
        print("Consonant")

"""4. Menu-Driven Program"""

print("1. Add")
print("2. Subtract")
print("3. Exit")

choice = int(input("Enter choice: "))

match choice:
    case 1:
        print("Addition Selected")
    case 2:
        print("Subtraction Selected")
    case 3:
        print("Exit")
    case _:
        print("Invalid Choice")

"""5. Grade Evaluation"""

grade = input("Enter Grade (A/B/C/D/F): ")

match grade.upper():
    case "A":
        print("Excellent")
    case "B":
        print("Very Good")
    case "C":
        print("Good")
    case "D":
        print("Pass")
    case "F":
        print("Fail")
    case _:
        print("Invalid Grade")

"""6. Traffic Signal"""

color = input("Enter signal color: ")

match color.lower():
    case "red":
        print("Stop")
    case "yellow":
        print("Ready")
    case "green":
        print("Go")
    case _:
        print("Invalid Color")

"""7. Display Weekday Names"""

day = int(input("Enter day number (1-7): "))

match day:
    case 1:
        print("Monday")
    case 2:
        print("Tuesday")
    case 3:
        print("Wednesday")
    case 4:
        print("Thursday")
    case 5:
        print("Friday")
    case 6:
        print("Saturday")
    case 7:
        print("Sunday")
    case _:
        print("Invalid Day")

"""8. Simple ATM Menu"""

print("1. Balance")
print("2. Deposit")
print("3. Withdraw")
print("4. Exit")

choice = int(input("Enter choice: "))

match choice:
    case 1:
        print("Balance: ₹5000")
    case 2:
        print("Deposit Selected")
    case 3:
        print("Withdraw Selected")
    case 4:
        print("Thank You")
    case _:
        print("Invalid Choice")

"""9. Classify Shapes"""

shape = input("Enter shape: ")

match shape.lower():
    case "circle":
        print("Round Shape")
    case "square":
        print("4 Equal Sides")
    case "triangle":
        print("3 Sides")
    case "rectangle":
        print("Opposite Sides Equal")
    case _:
        print("Unknown Shape")

"""10. Print Seasons Based on Month Number"""

month = int(input("Enter month number: "))

match month:
    case 12 | 1 | 2:
        print("Winter")
    case 3 | 4 | 5:
        print("Summer")
    case 6 | 7 | 8:
        print("Monsoon")
    case 9 | 10 | 11:
        print("Autumn")
    case _:
        print("Invalid Month")