# -*- coding: utf-8 -*-
"""Python functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FblxrGdZwqIIBoNajZeGc0QOZSXXgiIg

1. Write a Python function to print "Hello Python"
"""

def hello_python():
    print("Hello Python")
# Function calling
hello_python()

"""2. Function welcome() to take name input and print Welcome <name>"""

def welcome(name):
    print("Welcome", name)
name = input("Enter your name: ")
welcome(name)

"""3. Function to add two numbers and return result"""

def add(a, b):
    return a + b
x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
result = add(x, y)
print("Sum =", result)

"""4. Function to find square of a number"""

def square(num):
    return num * num
n = int(input("Enter number: "))
print("Square =", square(n))

"""5. Function to check even or odd"""

def check_even_odd(num):
    if num % 2 == 0:
        return "Even"
    else:
        return "Odd"
number = int(input("Enter number: "))
print(check_even_odd(number))

"""6. Function to find maximum of two numbers"""

def maximum(a,b):
    if a > b:
        return a
    else:
        return b
x=int(input("Enter first number: "))
y=int(input("Enter second number: "))
print("Maximum =", maximum(x,y))

"""7. Area of rectangle using length and breadth"""

def rectangle_area(length, breadth):
    return length * breadth
l=float(input("Enter length: "))
b=float(input("Enter breadth: "))
print("Area =", rectangle_area(l,b))

"""8. Celsius to Fahrenheit conversion"""

def celsius_to_fahrenheit(c):
    return (c * 9/5) + 32
temp=float(input("Enter Celsius: "))
print("Fahrenheit =", celsius_to_fahrenheit(temp))

"""9. Simple Interest Calculation"""

def simple_interest(p,r,t):
    return (p*r*t)/100
p=float(input("Enter Principal: "))
r=float(input("Enter Rate: "))
t=float(input("Enter Time: "))
print("Simple Interest =", simple_interest(p,r,t))

"""10. Factorial of a number"""

def factorial(num):
    fact=1
    for i in range(1,num+1):
        fact=fact*i
    return fact
n=int(input("Enter number: "))
print("Factorial =", factorial(n))

"""11. Function to find the largest number in a list"""

def find_largest(numbers):
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num
    return largest
numbers = [10, 25, 5, 40]
result = find_largest(numbers)
print("Largest number =", result)

"""12. Function to count number of vowels in a string"""

def count_vowels(text):
    count = 0
    vowels = "aeiouAEIOU"
    for ch in text:
        if ch in vowels:
            count += 1
    return count
string = input("Enter a string: ")
print("Number of vowels =", count_vowels(string))

"""13. Function to reverse a string"""

def reverse_string(text):
    return text[::-1]
word = input("Enter a string: ")
print("Reverse =", reverse_string(word))

"""14. Function to check whether a string is palindrome"""

def palindrome_check(text):
    if text == text[::-1]:
        return "Palindrome"
    else:
        return "Not Palindrome"
word = input("Enter word: ")
print(palindrome_check(word))

"""15. Function to count frequency of each character in a string"""

def character_frequency(text):
    frequency = {}
    for ch in text:
        if ch in frequency:
            frequency[ch] += 1
        else:
            frequency[ch] = 1
    return frequency
string = input("Enter string: ")
print(character_frequency(string))

"""16. Function accepts list and returns sum of all elements"""

def list_sum(numbers):
    total = 0
    for num in numbers:
        total += num
    return total
numbers = [10,20,30,40]
print("Sum =", list_sum(numbers))

"""17. Function to find second largest number in a list"""

def second_largest(numbers):
    numbers = list(set(numbers))
    numbers.sort()
    return numbers[-2]
numbers = [10,20,30,40,50]
print("Second largest =", second_largest(numbers))

"""18. Function to remove duplicate elements from a list"""

def remove_duplicates(numbers):
    result=[]
    for num in numbers:
        if num not in result:
            result.append(num)
    return result
numbers=[10,20,10,30,20,40]
print(remove_duplicates(numbers))

"""19. Function to check whether number is prime or not"""

def check_prime(num):
    if num <= 1:
        return "Not Prime"
    for i in range(2,num):
        if num%i==0:
            return "Not Prime"
    return "Prime"
number=int(input("Enter number: "))
print(check_prime(number))

"""20. Function to generate Fibonacci series up to n terms"""

def fibonacci(n):
    a=0
    b=1
    series=[]
    for i in range(n):
        series.append(a)
        a,b=b,a+b
    return series
terms=int(input("Enter number of terms: "))
print(fibonacci(terms))

"""21. Student details with default age"""

def student(name, age=18):
    print("Name:", name)
    print("Age:", age)
student("Divya",22)
student("Rahul", 20)

"""22. Salary with default bonus percentage"""

def salary(basic, bonus_percent=10):
    bonus = basic * bonus_percent / 100
    total = basic + bonus
    return total
print(salary(30000))
print(salary(30000, 20))

"""23. Calculate power with default exponent"""

def power(number, exponent=2):
    return number ** exponent
print(power(5))
print(power(5, 3))

"""24. Area of shapes using default values"""

def area(length=10, breadth=5):
    return length * breadth
print("Area:", area())
print("Area:", area(20, 10))

"""25. Employee information with optional department"""

def employee(name, salary, department="Not Assigned"):
    print("Name:", name)
    print("Salary:", salary)
    print("Department:", department)
employee("John", 50000)
employee("David", 60000, "IT")

"""26. Lambda function to add two numbers"""

add = lambda a, b: a + b
print(add(10, 20))

"""27. Check whether a number is even or odd"""

check = lambda n: "Even" if n % 2 == 0 else "Odd"
print(check(10))
print(check(7))

"""28. Use lambda with map() to square numbers"""

numbers = [1, 2, 3, 4]
result = list(map(lambda x: x ** 2, numbers))
print(result)

"""29. Use lambda with filter() to extract even numbers"""

numbers = [1, 2, 3, 4, 5, 6]
result = list(filter(lambda x: x % 2 == 0, numbers))
print(result)

"""30. Use lambda with sorted() to sort tuples by second value"""

data = [("A", 30), ("B", 10), ("C", 20)]
result = sorted(data, key=lambda x: x[1])
print(result)

"""31. Function using *args to find sum"""

def add(*args):
    return sum(args)
print(add(10, 20, 30, 40))

"""32. Function using **kwargs to display employee details"""

def employee(**kwargs):
    for key, value in kwargs.items():
        print(key, ":", value)
employee(name="John", age=25, salary=50000, department="IT")

"""33. Function accepting a list and returning minimum, maximum, average"""

def calculate(numbers):
    minimum = min(numbers)
    maximum = max(numbers)
    average = sum(numbers) / len(numbers)
    return minimum, maximum, average
numbers = [10, 20, 30, 40, 50]
minimum, maximum, average = calculate(numbers)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Average:", average)

"""34. Recursive function to calculate factorial"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)
print(factorial(5))

"""35. Recursive function to generate Fibonacci numbers"""

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)
n = 7
for i in range(n):
    print(fibonacci(i), end=" ")

"""36. Function decorator"""

def decorator(func):
    def wrapper():
        print("Function Started")
        func()
        print("Function Completed")
    return wrapper
@decorator
def hello():
    print("Hello Python")
hello()

"""37. Password strength checker"""

def check_password(password):
    if len(password) < 8:
        return "Password must contain minimum 8 characters"
    if not any(char.isdigit() for char in password):
        return "Password must contain a number"
    if not any(char.isupper() for char in password):
        return "Password must contain an uppercase letter"
    return "Strong Password"
print(check_password("Python123"))

"""38. Count words in a sentence"""

def count_words(sentence):
    return len(sentence.split())
sentence = input("Enter a sentence: ")
print("Number of words:", count_words(sentence))

"""39. Merge two dictionaries"""

def merge_dicts(dict1, dict2):
    result = dict1.copy()
    result.update(dict2)
    return result
d1 = {"a": 10, "b": 20}
d2 = {"c": 30, "d": 40}
print(merge_dicts(d1, d2))

"""40. Menu-Driven Calculator Using Functions"""

def addition(a, b):
    return a + b
def subtraction(a, b):
    return a - b
def multiplication(a, b):
    return a * b
def division(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b
while True:
    print("\n--- Calculator ---")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")
    choice = int(input("Enter your choice: "))
    if choice == 5:
        print("Calculator closed")
        break
    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))
    if choice == 1:
        print("Result:", addition(a, b))
    elif choice == 2:
        print("Result:", subtraction(a, b))
    elif choice == 3:
        print("Result:", multiplication(a, b))
    elif choice == 4:
        print("Result:", division(a, b))
    else:
        print("Invalid choice")

"""**Mini Project Function Questions**

41. Student Management System
"""

students = {}
def add_student():
    roll = input("Enter roll number: ")
    name = input("Enter student name: ")
    students[roll] = name
    print("Student added successfully")
def display_student():
    if not students:
        print("No students found")
    else:
        for roll, name in students.items():
            print("Roll:", roll, "Name:", name)
def search_student():
    roll = input("Enter roll number to search: ")

    if roll in students:
        print("Student found:", students[roll])
    else:
        print("Student not found")
def delete_student():
    roll = input("Enter roll number to delete: ")

    if roll in students:
        del students[roll]
        print("Student deleted")
    else:
        print("Student not found")
while True:
    print("\n1. Add Student")
    print("2. Display Students")
    print("3. Search Student")
    print("4. Delete Student")
    print("5. Exit")

    choice = int(input("Enter choice: "))

    if choice == 1:
        add_student()
    elif choice == 2:
        display_student()
    elif choice == 3:
        search_student()
    elif choice == 4:
        delete_student()
    elif choice == 5:
        break
    else:
        print("Invalid choice")

"""42. Bank Account System"""

balance = 0
def deposit():
    global balance
    amount = float(input("Enter deposit amount: "))
    if amount > 0:
        balance += amount
        print("Amount deposited successfully")
    else:
        print("Invalid amount")
def withdraw():
    global balance
    amount = float(input("Enter withdrawal amount: "))
    if amount <= 0:
        print("Invalid amount")
    elif amount > balance:
        print("Insufficient balance")
    else:
        balance -= amount
        print("Amount withdrawn successfully")
def check_balance():
    print("Current Balance:", balance)
while True:
    print("\n--- Bank Account ---")
    print("1. Deposit")
    print("2. Withdraw")
    print("3. Check Balance")
    print("4. Exit")
    choice = int(input("Enter choice: "))
    if choice == 1:
        deposit()
    elif choice == 2:
        withdraw()
    elif choice == 3:
        check_balance()
    elif choice == 4:
        break
    else:
        print("Invalid choice")

"""43. Library Management System"""

books = []
def add_book():
    book = input("Enter book name: ")
    books.append(book)
    print("Book added successfully")
def issue_book():
    book = input("Enter book name to issue: ")
    if book in books:
        books.remove(book)
        print("Book issued successfully")
    else:
        print("Book not available")
def return_book():
    book = input("Enter book name to return: ")
    books.append(book)
    print("Book returned successfully")
while True:
    print("\n--- Library Management ---")
    print("1. Add Book")
    print("2. Issue Book")
    print("3. Return Book")
    print("4. Display Books")
    print("5. Exit")
    choice = int(input("Enter choice: "))
    if choice == 1:
        add_book()
    elif choice == 2:
        issue_book()
    elif choice == 3:
        return_book()
    elif choice == 4:
        print("Available Books:", books)
    elif choice == 5:
        break
    else:
        print("Invalid choice")

"""44. Quiz Application Using Functions"""

def quiz():
    questions = [
        ("What is the capital of India?", "delhi"),
        ("Which language is used for AI and Data Science?", "python"),
        ("What is 5 + 5?", "10")
    ]

    score = 0

    for question, answer in questions:
        user_answer = input(question + " ")

        if user_answer.lower() == answer:
            print("Correct!")
            score += 1
        else:
            print("Wrong!")

    print("\nYour Score:", score, "/", len(questions))

quiz()

"""45. Contact Management System"""

contacts = {}
def add_contact():
    name = input("Enter name: ")
    phone = input("Enter phone number: ")

    contacts[name] = phone
    print("Contact added successfully")
def display_contacts():
    if not contacts:
        print("No contacts found")
    else:
        for name, phone in contacts.items():
            print("Name:", name, "| Phone:", phone)
def search_contact():
    name = input("Enter name to search: ")

    if name in contacts:
        print("Phone:", contacts[name])
    else:
        print("Contact not found")
def delete_contact():
    name = input("Enter name to delete: ")

    if name in contacts:
        del contacts[name]
        print("Contact deleted successfully")
    else:
        print("Contact not found")
while True:
    print("\n--- Contact Management System ---")
    print("1. Add Contact")
    print("2. Display Contacts")
    print("3. Search Contact")
    print("4. Delete Contact")
    print("5. Exit")
    choice = int(input("Enter choice: "))
    if choice == 1:
        add_contact()
    elif choice == 2:
        display_contacts()
    elif choice == 3:
        search_contact()
    elif choice == 4:
        delete_contact()
    elif choice == 5:
        print("Program ended")
        break
    else:
        print("Invalid choice")