# -*- coding: utf-8 -*-
"""PYTHON LEARNING .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxH0Yex3PsBW1Z5MHa94iIv78SniW7Ra

**INTRODUCTION**

# 1. VARIABLES, DATA TYPES, TYPE CASTING
"""

name = "Sivaranjani"
age = 23
gpa = 8.9
is_student = True

print(type(name), type(age), type(gpa), type(is_student))

# Type casting
age_str = str(age)
gpa_int = int(gpa)
str_to_float = float("9.5")
print(age_str, type(age_str))
print(gpa_int, type(gpa_int))
print(str_to_float, type(str_to_float))

"""# 2. USER INPUT & PRINT"""

user_name = input("Enter your name: ")
print("Hello,", user_name)
print(f"Welcome {user_name}, formatted with f-string!")

"""# 3. IDENTIFIERS (naming rules)"""

student_name = "Ravi"      # valid
_score = 90                # valid, starts with underscore
score2 = 85                # valid, number not at start
print(student_name, _score, score2)

"""# 4. OPERATORS"""

a, b = 10, 3

# Arithmetic
print(a + b, a - b, a * b, a / b, a % b, a ** b, a // b)

# Assignment
c = 5
c += 2; print(c)
c *= 3; print(c)

# Comparison
print(a > b, a == b, a != b, a <= b)

# Logical
print(a > 5 and b < 5)
print(a > 5 or b > 5)
print(not(a > 5))

# Membership
fruits = ["apple", "banana", "mango"]
print("apple" in fruits)
print("grape" not in fruits)

"""# 5. LOOPS — WHILE, FOR, NESTED, BREAK, CONTINUE, PASS"""

# While loop
i = 1
while i <= 5:
    print("While loop:", i)
    i += 1

# For loop
for num in range(1, 6):
    print("For loop:", num)

# Nested loop
for i in range(1, 4):
    for j in range(1, 3):
        print(f"i={i}, j={j}")

# Break
for num in range(10):
    if num == 5:
        break
    print("Break demo:", num)

# Continue
for num in range(5):
    if num == 2:
        continue
    print("Continue demo:", num)

# Pass
for num in range(3):
    if num == 1:
        pass  # placeholder, does nothing
    print("Pass demo:", num)

"""# 6. MATH FUNCTIONS"""

import math
print(math.sqrt(25))
print(math.factorial(5))
print(math.ceil(4.2), math.floor(4.8))
print(math.pow(2, 3))

"""# 7. LISTS"""

students = ["Ravi", "Anitha", "Suresh", "Priya"]
students.append("Karthik")
students.remove("Suresh")
print(students)
print(students[0], students[-1])
print(students[1:3])

"""# 8. TUPLES — PACKING & UNPACKING"""

student_info = ("Ravi", 23, "CSE")   # packing
name, age, dept = student_info       # unpacking
print(name, age, dept)
print(student_info[0])

"""# 9. DICTIONARIES"""

student = {"name": "Ravi", "department": "CSE", "gpa": 8.9}
print(student["name"])
student["gpa"] = 9.1
student["email"] = "ravi@mail.com"
print(student)
for key, value in student.items():
    print(key, ":", value)

"""# 10. SETS & SET OPERATIONS"""

set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))
print(set_a.symmetric_difference(set_b))

"""# 11. STRINGS & STRING FUNCTIONS"""

text = "Data Engineering"
print(text.upper())
print(text.lower())
print(text.replace("Data", "Big Data"))
print(text.split(" "))
print(text[0:4])
print(len(text))
print(text.strip())

"""# 12. ARRAYS & ARRAY OPERATIONS (using NumPy)"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(arr.mean(), arr.sum(), arr.max(), arr.min())
print(arr * 2)
print(arr[arr > 20])

"""# 13. FUNCTIONS — REGULAR, RECURSIVE, LAMBDA, BUILT-IN"""

# Regular function
def greet(name):
    return f"Hello, {name}!"
print(greet("Sivaranjani"))

# Recursive function
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)
print(factorial(5))

# Lambda function
square = lambda x: x * x
print(square(6))

# Built-in functions
nums = [4, 2, 9, 1, 7]
print(len(nums), max(nums), min(nums), sorted(nums))
print(list(map(lambda x: x*2, nums)))
print(list(filter(lambda x: x > 4, nums)))

"""# 14. LOCAL & GLOBAL VARIABLES"""

counter = 10  # global variable

def update_counter():
    global counter
    counter += 5   # modifies the global variable
    local_val = 100  # local to this function
    print("Inside function:", counter, local_val)

update_counter()
print("Outside function:", counter)

"""# 15. EXCEPTION HANDLING & ERRORS"""

try:
    result = 10 / 0
except ZeroDivisionError as e:
    print("Error caught:", e)
finally:
    print("This always runs")

try:
    num = int("abc")
except ValueError as e:
    print("Value error caught:", e)

# Custom exception
class InvalidGPAError(Exception):
    pass

def check_gpa(gpa):
    if gpa > 10:
        raise InvalidGPAError("GPA cannot be greater than 10")
    return gpa

try:
    check_gpa(11)
except InvalidGPAError as e:
    print("Custom error:", e)

"""# 16. OOP CONCEPTS — CLASS, OBJECT, CONSTRUCTOR, SELF"""

class Student:
    college_name = "Anna University"   # class variable

    def __init__(self, name, department, gpa):   # constructor
        self.name = name          # instance variable
        self.department = department
        self.gpa = gpa

    def display(self):
        print(f"{self.name} | {self.department} | GPA: {self.gpa}")

s1 = Student("Ravi", "CSE", 8.9)
s2 = Student("Anitha", "ECE", 7.8)
s1.display()
s2.display()
print(s1.college_name)

"""# 17. ACCESS MODIFIERS"""

class BankAccount:
    def __init__(self, balance):
        self.balance = balance          # public
        self._acc_type = "Savings"      # protected (convention)
        self.__pin = 1234               # private (name mangled)

    def show_balance(self):
        print("Balance:", self.balance)

    def __show_pin(self):               # private method
        print("PIN:", self.__pin)

acc = BankAccount(5000)
acc.show_balance()
print(acc._acc_type)          # accessible but discouraged
# print(acc.__pin)            # AttributeError — private, not directly accessible

"""# 18. FILE HANDLING"""

# Write to a file
with open("students.txt", "w") as f:
    f.write("Ravi,CSE,8.9\n")
    f.write("Anitha,ECE,7.8\n")

# Read from a file
with open("students.txt", "r") as f:
    content = f.read()
    print(content)

# Append to a file
with open("students.txt", "a") as f:
    f.write("Suresh,Mech,6.5\n")

with open("students.txt", "r") as f:
    for line in f:
        print(line.strip())

"""# 19. NUMPY & PANDAS BASICS (Data Engineering Essentials)"""

import pandas as pd

data = {
    "name": ["Ravi", "Anitha", "Suresh", "Priya"],
    "department": ["CSE", "ECE", "Mech", "CSE"],
    "gpa": [8.9, 7.8, 6.5, 9.2]
}
df = pd.DataFrame(data)
print(df)
print(df.describe())
print(df[df["gpa"] > 8])
print(df.groupby("department")["gpa"].mean())