# -*- coding: utf-8 -*-
"""SCD using Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GcZluuaigOMKSUUzD8A1M_A30GDrlK3J
"""

import pandas as pd


baseline = [
    (101, "Wireless Mouse", "Electronics", 799, "TechSource"),
    (102, "Office Chair", "Furniture", 4500, "ComfortWorks"),
    (103, "Notebook Set", "Stationery", 150, "PaperPlus"),
    (104, "LED Monitor", "Electronics", 9500, "TechSource"),
    (105, "Standing Desk", "Furniture", 12000, "ComfortWorks"),
    (106, "Backpack", "Accessories", 1200, "UrbanGear"),
    (107, "Water Bottle", "Accessories", 350, "UrbanGear"),
    (108, "Desk Lamp", "Furniture", 899, "ComfortWorks"),
    (109, "Bluetooth Speaker", "Electronics", 2500, "TechSource"),
    (110, "Notebook Cover", "Stationery", 99, "PaperPlus"),
]
cols = ["ProductID", "ProductName", "Category", "Price", "Supplier"]

df_type1 = pd.DataFrame(baseline, columns=cols)

df_type2 = pd.DataFrame(baseline, columns=cols)
df_type2["StartDate"] = pd.Timestamp("2026-01-01")
df_type2["EndDate"] = pd.NaT
df_type2["IsCurrent"] = 1

df_type3 = pd.DataFrame(baseline, columns=cols)
df_type3["PreviousCategory"] = None
df_type3["PreviousPrice"] = None
df_type3["PreviousSupplier"] = None

CHANGES = [
    (101, {"Price": 699}),
    (104, {"Supplier": "VisionTech"}),
    (106, {"Category": "Travel"}),
    (108, {"Price": 749}),
]

# SCD Type 1 — overwrite in place


def scd1_update(df, product_id, updates_dict):
    mask = df["ProductID"] == product_id
    for col, new_val in updates_dict.items():
        df.loc[mask, col] = new_val
    return df

for pid, changes in CHANGES:
    df_type1 = scd1_update(df_type1, pid, changes)


#  SCD Type 2 — expire current row, append new row


def scd2_update(df, product_id, updates_dict):
    today = pd.Timestamp.today().normalize()

    current_mask = (df["ProductID"] == product_id) & (df["IsCurrent"] == 1)
    df.loc[current_mask, "EndDate"] = today
    df.loc[current_mask, "IsCurrent"] = 0

    new_row = df.loc[current_mask].copy()
    # current_mask row was just expired; rebuild the new version from it
    new_row = df[(df["ProductID"] == product_id)].iloc[[-1]].copy()
    for col, new_val in updates_dict.items():
        new_row[col] = new_val
    new_row["StartDate"] = today
    new_row["EndDate"] = pd.NaT
    new_row["IsCurrent"] = 1

    return pd.concat([df, new_row], ignore_index=True)

for pid, changes in CHANGES:
    df_type2 = scd2_update(df_type2, pid, changes)

print("SCD Type 2 — currently active rows:")
print(df_type2[df_type2["IsCurrent"] == 1])


#  SCD Type 3 — shift old value into "Previous" column


def scd3_update(df, product_id, updates_dict):
    mask = df["ProductID"] == product_id
    for col, new_val in updates_dict.items():
        prev_col = f"Previous{col}"
        df.loc[mask, prev_col] = df.loc[mask, col]
        df.loc[mask, col] = new_val
    return df

for pid, changes in CHANGES:
    df_type3 = scd3_update(df_type3, pid, changes)



print("\n=== Type 1 (overwrite) ===")
print(df_type1)

print("\n=== Type 2 (full history) ===")
print(df_type2.sort_values(["ProductID", "StartDate"]))

print("\n=== Type 3 (one-step-back) ===")
print(df_type3)