# -*- coding: utf-8 -*-
"""String assessment 10/july/26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0bBFbCTF5vpOcWjq-miLZcmXleWi1FR

**1. Find the length of a string without using len()**
"""

string = input("Enter a string: ")

count = 0
for i in string:
    count += 1

print("Length of the string is:", count)

"""**2. Reverse a string using a loop**"""

string = input("Enter a string: ")

reverse = ""
for i in string:
    reverse = i + reverse

print("Reversed string:", reverse)

"""**3. Count the number of words in a sentence**"""

sentence = input("Enter a sentence: ")

count = 1
for i in sentence:
    if i == " ":
        count += 1

print("Number of words:", count)

"""**4. Find the largest element in an array**"""

arr = list(map(int, input("Enter numbers separated by space: ").split()))

largest = arr[0]

for i in arr:
    if i > largest:
        largest = i

print("Largest element:", largest)

"""**5. Find the second largest number in an array**"""

arr = list(map(int, input("Enter numbers separated by space: ").split()))

largest = second = float('-inf')

for i in arr:
    if i > largest:
        second = largest
        largest = i
    elif i > second and i != largest:
        second = i

print("Second largest element:", second)

"""**6. Remove duplicate elements from an array**"""

arr = list(map(int, input("Enter numbers separated by space: ").split()))

result = []

for i in arr:
    if i not in result:
        result.append(i)

print("Array after removing duplicates:", result)

"""**7. Merge two arrays**"""

arr1 = list(map(int, input("Enter first array: ").split()))
arr2 = list(map(int, input("Enter second array: ").split()))

merged = arr1 + arr2

print("Merged array:", merged)

"""**8. Find common elements between two arrays**"""

arr1 = list(map(int, input("Enter first array: ").split()))
arr2 = list(map(int, input("Enter second array: ").split()))

common = []

for i in arr1:
    if i in arr2 and i not in common:
        common.append(i)

print("Common elements:", common)

"""**9. Check whether two strings are anagrams**"""

str1 = input("Enter first string: ")
str2 = input("Enter second string: ")

if sorted(str1) == sorted(str2):
    print("The strings are anagrams.")
else:
    print("The strings are not anagrams.")

"""**10. Sort an array without using sort()**"""

arr = list(map(int, input("Enter numbers separated by space: ").split()))

for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] > arr[j]:
            arr[i], arr[j] = arr[j], arr[i]

print("Sorted array:", arr)