# -*- coding: utf-8 -*-
"""while loop assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wt1LugkJqPd6s27TkqfP4P8ETLR5L3qg

1. Print numbers from 1 to 10
"""

i = 1

while i <= 10:
    print(i)
    i += 1

"""2. Print numbers from 10 to 1"""

i = 10

while i >= 1:
    print(i)
    i -= 1

"""3. Print even numbers from 1 to 50"""

i = 2

while i <= 50:
    print(i)
    i += 2

"""4. Print odd numbers from 1 to 50"""

i = 1

while i <= 50:
    print(i)
    i += 2

"""5. Print multiples of 5 from 5 to 100"""

i = 5

while i <= 100:
    print(i)
    i += 5

"""6. Multiplication Table"""

num = int(input("Enter a number: "))

i = 1

while i <= 10:
    print(num, "x", i, "=", num * i)
    i += 1

"""7. Sum of numbers from 1 to N"""

n = int(input("Enter N: "))

i = 1
sum = 0

while i <= n:
    sum = sum + i
    i += 1

print("Sum =", sum)

"""8. Product of numbers from 1 to N"""

n = int(input("Enter N: "))

i = 1
product = 1

while i <= n:
    product = product * i
    i += 1

print("Product =", product)

"""9. Factorial of a Number"""

n = int(input("Enter a number: "))

fact = 1
i = 1

while i <= n:
    fact = fact * i
    i += 1

print("Factorial =", fact)

"""10. Count the Number of Digits"""

num = int(input("Enter a number: "))

count = 0

while num > 0:
    num = num // 10
    count += 1

print("Digits =", count)

"""11. Reverse a Number"""

num = int(input("Enter a number: "))

reverse = 0

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num = num // 10

print("Reverse =", reverse)

"""12. Sum of Digits"""

num = int(input("Enter a number: "))

sum = 0

while num > 0:
    digit = num % 10
    sum = sum + digit
    num = num // 10

print("Sum =", sum)

"""13. Largest Digit"""

num = int(input("Enter a number: "))

largest = 0

while num > 0:
    digit = num % 10

    if digit > largest:
        largest = digit

    num = num // 10

print("Largest Digit =", largest)

"""14. Smallest Digit"""

num = int(input("Enter a number: "))

smallest = 9

while num > 0:
    digit = num % 10

    if digit < smallest:
        smallest = digit

    num = num // 10

print("Smallest Digit =", smallest)

"""15. Palindrome Number"""

num = int(input("Enter a number: "))

temp = num
reverse = 0

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num = num // 10

if temp == reverse:
    print("Palindrome")
else:
    print("Not Palindrome")

"""16. Armstrong Number"""

num = int(input("Enter a number: "))

temp = num
sum = 0

while num > 0:
    digit = num % 10
    sum = sum + digit ** 3
    num = num // 10

if temp == sum:
    print("Armstrong Number")
else:
    print("Not Armstrong Number")

"""17. Pattern"""

i = 1

while i <= 5:
    j = 1

    while j <= i:
        print("*", end="")
        j += 1

    print()
    i += 1

"""18. Pattern"""

i = 5

while i >= 1:
    j = 1

    while j <= i:
        print("*", end="")
        j += 1

    print()
    i -= 1

"""19. Pattern"""

i = 1

while i <= 5:
    j = 1

    while j <= i:
        print(j, end="")
        j += 1

    print()
    i += 1

"""20. Pattern"""

i = 1

while i <= 5:
    j = 5

    while j >= 6 - i:
        print(j, end="")
        j -= 1

    print()
    i += 1

"""21. Menu Driven Calculator"""

choice = 0

while choice != 5:

    print("1.Addition")
    print("2.Subtraction")
    print("3.Multiplication")
    print("4.Division")
    print("5.Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))
        print("Answer =", a + b)

    elif choice == 2:
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))
        print("Answer =", a - b)

    elif choice == 3:
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))
        print("Answer =", a * b)

    elif choice == 4:
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))
        print("Answer =", a / b)

    elif choice == 5:
        print("Program Ended")

    else:
        print("Invalid Choice")

"""22. Password Check"""

password = ""

while password != "python123":
    password = input("Enter Password: ")

    if password != "python123":
        print("Wrong")

print("Access Granted")

"""23. Sum Until User Enters 0"""

sum = 0

num = int(input("Enter number: "))

while num != 0:
    sum = sum + num
    num = int(input("Enter number: "))

print("Sum =", sum)

"""24. Count Numbers Until Negative Number"""

count = 0

num = int(input("Enter number: "))

while num >= 0:
    count += 1
    num = int(input("Enter number: "))

print("Count =", count)

"""25. Number Guessing Game"""

secret = 5
guess = 0
attempts = 0

while guess != secret:
    guess = int(input("Guess the number: "))
    attempts += 1

    if guess == secret:
        print("Correct!")
    else:
        print("Wrong!")

print("Attempts =", attempts)