# -*- coding: utf-8 -*-
"""Numpy and Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIgNHRAVmvytx-sPU-hR9H6hFVR_HhMk

1.Create a 1D NumPy array of integers 1–20. Reshape it into a 4×5 matrix.
"""

import numpy as np

# Create a 1D array
arr = np.arange(1, 21)

print("1D Array:")
print(arr)

# Reshape into 4x5 matrix
matrix = arr.reshape(4, 5)

print("\n4x5 Matrix:")
print(matrix)

"""2.Given a 2D array, find the sum of each row and each column separately."""

import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Array:")
print(arr)

# Row sum
row_sum = np.sum(arr, axis=1)

# Column sum
col_sum = np.sum(arr, axis=0)

print("\nRow Sum:")
print(row_sum)

print("\nColumn Sum:")
print(col_sum)

"""3.Create two arrays of the same shape and perform element-wise addition, subtraction, multiplication, and division."""

import numpy as np

# Create arrays
A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([[2, 4, 6],
              [8, 10, 12]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nAddition:")
print(A + B)

print("\nSubtraction:")
print(A - B)

print("\nMultiplication:")
print(A * B)

print("\nDivision:")
print(A / B)

"""4.Generate a 5×5 array of random integers between 10 and 100. Find the maximum, minimum, mean, and standard deviation."""

import numpy as np

# Generate random array
arr = np.random.randint(10, 101, (5, 5))

print("Random 5x5 Array:")
print(arr)

print("\nMaximum Value:")
print(np.max(arr))

print("\nMinimum Value:")
print(np.min(arr))

print("\nMean:")
print(np.mean(arr))

print("\nStandard Deviation:")
print(np.std(arr))

"""5.Given an array [15, 8, 23, 4, 42, 16], use boolean indexing to extract only values greater than 15."""

import numpy as np

# Create array
arr = np.array([15, 8, 23, 4, 42, 16])

print("Original Array:")
print(arr)

# Boolean indexing
result = arr[arr > 15]

print("\nValues Greater Than 15:")
print(result)

"""6.Create a NumPy array with some NaN values, then use np.isnan() to identify and replace them with the array's mean."""

import numpy as np

# Create array with NaN values
arr = np.array([10, 20, np.nan, 40, np.nan, 60])

print("Original Array:")
print(arr)

# Find NaN values
print("\nNaN Positions:")
print(np.isnan(arr))

# Calculate mean excluding NaN
mean_value = np.nanmean(arr)

# Replace NaN values with mean
arr[np.isnan(arr)] = mean_value

print("\nMean (excluding NaN):", mean_value)

print("\nArray after replacing NaN:")
print(arr)

"""7.Demonstrate broadcasting: add a 1D array of shape (3,) to a 2D array of shape (3,3) and explain what happens."""

import numpy as np

# 3x3 Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1D Array
arr = np.array([10, 20, 30])

print("2D Matrix:")
print(matrix)

print("\n1D Array:")
print(arr)

# Broadcasting
result = matrix + arr

print("\nResult after Broadcasting:")
print(result)

"""8.Use np.where() to create a new array that labels each value in [45, 67, 23, 89, 12] as "High" if above 50, else "Low"."""

import numpy as np

arr = np.array([45, 67, 23, 89, 12])

print("Original Array:")
print(arr)

labels = np.where(arr > 50, "High", "Low")

print("\nLabels:")
print(labels)

"""9.Stack two arrays vertically using np.vstack() and horizontally using np.hstack()."""

import numpy as np

# Create arrays
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

# Vertical Stack
vertical = np.vstack((A, B))

print("\nVertical Stack (vstack):")
print(vertical)

# Horizontal Stack
horizontal = np.hstack((A, B))

print("\nHorizontal Stack (hstack):")
print(horizontal)

"""10.Create an identity matrix of size 4×4 using np.eye(), and compute its transpose."""

import numpy as np

# Create identity matrix
identity = np.eye(4)

print("Identity Matrix:")
print(identity)

# Transpose
transpose = identity.T

print("\nTranspose of Identity Matrix:")
print(transpose)

"""11.Create a DataFrame with columns EmployeeID, Name, Department, Salary, JoiningDate for at least 8 employees."""

import pandas as pd

# Create employee DataFrame
data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "Marketing", "IT"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 65000, 52000, 75000],
    "JoiningDate": [
        "2021-01-15",
        "2020-06-20",
        "2022-03-10",
        "2019-11-25",
        "2023-05-18",
        "2021-08-30",
        "2022-07-12",
        "2020-02-14"
    ]
}

df = pd.DataFrame(data)

# Convert JoiningDate to datetime
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])

print("Employee DataFrame:")
print(df)

"""12.Use .info() and .describe() to inspect the DataFrame's structure and summary statistics."""

import pandas as pd

# Display DataFrame information
print("DataFrame Information:")
df.info()

# Display summary statistics
print("\nSummary Statistics:")
print(df.describe())

"""13.Filter employees who joined after a specific date AND earn above a given salary threshold."""

import pandas as pd

# Filter employees
filtered_df = df[
    (df["JoiningDate"] > "2021-01-01") &
    (df["Salary"] > 50000)
]

print("Filtered Employees:")
print(filtered_df)

"""14.Group by Department and compute the average, minimum, and maximum salary per department using .groupby().agg()."""

import pandas as pd

# Group by Department
grouped = df.groupby("Department").agg({
    "Salary": ["mean", "min", "max"]
})

print("Department-wise Salary Statistics:")
print(grouped)

"""15.Introduce some NaN values into the Salary column, then demonstrate .isnull(), .dropna(), and .fillna() (with mean imputation)."""

import pandas as pd
import numpy as np

# Create a copy of the DataFrame
df_nan = df.copy()

# Introduce NaN values
df_nan.loc[2, "Salary"] = np.nan
df_nan.loc[5, "Salary"] = np.nan

print("DataFrame with NaN values:")
print(df_nan)

# Check for null values
print("\nNull Values:")
print(df_nan.isnull())

# Drop rows containing NaN values
print("\nAfter dropna():")
print(df_nan.dropna())

# Fill NaN with mean salary
mean_salary = df_nan["Salary"].mean()

df_nan["Salary"] = df_nan["Salary"].fillna(mean_salary)

print("\nMean Salary:", mean_salary)

print("\nAfter fillna():")
print(df_nan)

"""16.Sort the DataFrame by Salary descending, then by Department ascending (multi-column sort)."""

import pandas as pd

# Sort by Salary (descending) and Department (ascending)
sorted_df = df.sort_values(by=["Salary", "Department"],
                           ascending=[False, True])

print("Sorted DataFrame:")
print(sorted_df)

"""17.Use .apply() with a custom function to create a new column classifying employees as Senior, Mid, or Junior based on salary."""

import pandas as pd

# Function to classify employees
def classify_salary(salary):
    if salary >= 70000:
        return "Senior"
    elif salary >= 55000:
        return "Mid"
    else:
        return "Junior"

# Apply the function
df["Category"] = df["Salary"].apply(classify_salary)

print("Employee Classification:")
print(df)

"""18.Merge two DataFrames—an employee DataFrame and a department-budget DataFrame—using pd.merge(), demonstrating inner, left, right, and outer joins."""

import pandas as pd

# Department Budget DataFrame
budget_df = pd.DataFrame({
    "Department": ["HR", "IT", "Finance", "Marketing", "Sales"],
    "Budget": [200000, 500000, 350000, 250000, 400000]
})

print("Employee DataFrame:")
print(df)

print("\nDepartment Budget DataFrame:")
print(budget_df)

# Inner Join
inner_join = pd.merge(df, budget_df, on="Department", how="inner")

# Left Join
left_join = pd.merge(df, budget_df, on="Department", how="left")

# Right Join
right_join = pd.merge(df, budget_df, on="Department", how="right")

# Outer Join
outer_join = pd.merge(df, budget_df, on="Department", how="outer")

print("\nInner Join:")
print(inner_join)

print("\nLeft Join:")
print(left_join)

print("\nRight Join:")
print(right_join)

print("\nOuter Join:")
print(outer_join)

"""19.Use pivot_table() to create a summary showing average salary by Department and by a second categorical column (City)."""

import pandas as pd

# Add City column
df["City"] = [
    "Chennai",
    "Bangalore",
    "Chennai",
    "Hyderabad",
    "Bangalore",
    "Chennai",
    "Hyderabad",
    "Bangalore"
]

# Create Pivot Table
pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="mean"
)

print("Pivot Table:")
print(pivot)

"""20.Export the cleaned DataFrame to a CSV file using .to_csv(), then read it back with pd.read_csv() and confirm the data matches."""

import pandas as pd

# Export DataFrame
df.to_csv("employees.csv", index=False)

print("Data exported successfully.")

# Read the CSV file
new_df = pd.read_csv("employees.csv")

print("\nImported Data:")
print(new_df)

# Verify the data
if df.shape == new_df.shape:
    print("\nThe imported data matches the original DataFrame.")
else:
    print("\nThe imported data does not match the original DataFrame.")