# -*- coding: utf-8 -*-
"""Pyspark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfG0TVdq0ARDOGY2vghDDOuFWCu4t5I3

**SECTION A**

1.Install PySpark via pip, write a script that creates a SparkSession named "AssignmentSetup" running in local[2] mode, print the Spark version, then stop the session cleanly.
"""

# Install PySpark (Run this only once in Google Colab)
!pip install pyspark

# Import SparkSession
from pyspark.sql import SparkSession

# Create SparkSession
spark = SparkSession.builder \
    .appName("AssignmentSetup") \
    .master("local[2]") \
    .getOrCreate()

# Print Spark version
print("Spark Version:", spark.version)

# Stop Spark session
spark.stop()

print("Spark Session stopped successfully.")

"""2.Explain the difference between running pyspark (interactive shell) and spark-submit script.py (script execution). When would you use each?"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("InteractiveExample") \
    .master("local[*]") \
    .getOrCreate()

data = [("Alice", 25),
        ("Bob", 30),
        ("Charlie", 28)]

df = spark.createDataFrame(data, ["Name", "Age"])

df.show()

spark.stop()

"""**SECTION B**

1.Create a SparkSession with 4 local cores. Load any small DataFrame and call .rdd.getNumPartitions(). Explain what determines this number.
"""

from pyspark.sql import SparkSession

# Create SparkSession with 4 local cores
spark = SparkSession.builder \
    .appName("SparkArchitecture") \
    .master("local[4]") \
    .getOrCreate()

# Sample Data
data = [
    (101, "Alice", 45000),
    (102, "Bob", 55000),
    (103, "Charlie", 60000),
    (104, "David", 70000),
    (105, "Eva", 50000),
    (106, "Frank", 65000)
]

columns = ["ID", "Name", "Salary"]

# Create DataFrame
df = spark.createDataFrame(data, columns)

# Display DataFrame
print("Employee DataFrame")
df.show()

# Display number of partitions
print("Number of Partitions:", df.rdd.getNumPartitions())

# Stop Spark
spark.stop()

"""2.Given a chain of .filter() → .groupBy() → .orderBy() → .show(), identify how many Jobs, Stages, and Tasks this would likely produce, and explain which operations cause shuffle boundaries."""

from pyspark.sql import SparkSession
from pyspark.sql.functions import avg

spark = SparkSession.builder \
    .appName("JobsStagesTasks") \
    .master("local[4]") \
    .getOrCreate()

# Sample Data
data = [
    ("HR", 45000),
    ("IT", 60000),
    ("IT", 70000),
    ("Finance", 55000),
    ("HR", 50000),
    ("Finance", 65000)
]

df = spark.createDataFrame(data, ["Department", "Salary"])

# Transformation Chain
result = df.filter(df.Salary > 45000) \
           .groupBy("Department") \
           .agg(avg("Salary").alias("AverageSalary")) \
           .orderBy("AverageSalary")

# Action
result.show()

spark.stop()

"""3.Explain, in your own words, the difference between the Driver, the Cluster Manager, and Executors.

**Driver:**The Driver is the main part of the Spark application. It creates the SparkSession/SparkContext, reads our program, divides it into jobs, stages, and tasks, and sends these tasks to the Cluster Manager. After the Executors finish their work, the Driver collects the final results.

**Cluster Manager:**The Cluster Manager receives the tasks from the Driver and manages the available resources. It starts the Executors and distributes the tasks among them. We can use YARN, Kubernetes or Standalone as the Cluster Manager.

**Executors:**The Executors do the actual work. They execute the tasks assigned to them, process the data, cache intermediate data if needed, maintain log information, and send the final results back to the Driver.

**SECTION C**

1.Create a DataFrame containing employee records (EmpID, Name, Department, Salary, JoinDate). Show how to calculate:
Average Salary
Maximum Salary
Minimum Salary
Employee Count
Department-wise Average Salary
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, max, min, count

# Create Spark Session
spark = SparkSession.builder \
    .appName("EmployeeDataFrame") \
    .master("local[*]") \
    .getOrCreate()

# Employee Data
data = [
    (101, "Alice", "HR", 45000, "2022-01-15"),
    (102, "Bob", "IT", 60000, "2021-05-20"),
    (103, "Charlie", "Finance", 55000, "2020-03-10"),
    (104, "David", "IT", 70000, "2019-08-25"),
    (105, "Eva", "HR", 48000, "2023-02-18"),
    (106, "Frank", "Finance", 65000, "2021-07-30")
]

columns = ["EmpID", "Name", "Department", "Salary", "JoinDate"]

# Create DataFrame
df = spark.createDataFrame(data, columns)

print("Employee DataFrame")
df.show()

# Average Salary
print("Average Salary")
df.select(avg("Salary")).show()

# Maximum Salary
print("Maximum Salary")
df.select(max("Salary")).show()

# Minimum Salary
print("Minimum Salary")
df.select(min("Salary")).show()

# Employee Count
print("Employee Count")
df.select(count("EmpID")).show()

# Department-wise Average Salary
print("Department-wise Average Salary")
df.groupBy("Department").agg(avg("Salary").alias("AverageSalary")).show()

"""2.Using the employee DataFrame, partition by Department and order by Salary descending. Demonstrate rank(), dense_rank(), row_number(), and ntile(3). Explain the difference between them."""

from pyspark.sql import SparkSession
from pyspark.sql.window import Window
from pyspark.sql.functions import rank, dense_rank, row_number, ntile

spark = SparkSession.builder \
    .appName("WindowFunctions") \
    .master("local[*]") \
    .getOrCreate()

# Window Specification
windowSpec = Window.partitionBy("Department").orderBy(df.Salary.desc())

result = df.withColumn("Rank", rank().over(windowSpec)) \
           .withColumn("DenseRank", dense_rank().over(windowSpec)) \
           .withColumn("RowNumber", row_number().over(windowSpec)) \
           .withColumn("NTile", ntile(3).over(windowSpec))

result.show()

"""3.Using the employee DataFrame ordered by JoinDate, demonstrate lag() and lead() to compare each employee's salary with the previous and next employee."""

from pyspark.sql import SparkSession
from pyspark.sql.window import Window
from pyspark.sql.functions import lag, lead

spark = SparkSession.builder \
    .appName("LagLeadExample") \
    .master("local[*]") \
    .getOrCreate()

# Window Specification
windowSpec = Window.orderBy("JoinDate")

result = df.withColumn("PreviousSalary", lag("Salary",1).over(windowSpec)) \
           .withColumn("NextSalary", lead("Salary",1).over(windowSpec))

result.show()

"""4.Using a window ordered by JoinDate, compute a running total of salaries (running_salary_total) so that each row contains the cumulative salary up to that employee. Explain how the window frame works."""

from pyspark.sql import SparkSession
from pyspark.sql.window import Window
from pyspark.sql.functions import sum

# Create Spark Session
spark = SparkSession.builder \
    .appName("RunningTotal") \
    .master("local[*]") \
    .getOrCreate()

# Window Specification
windowSpec = Window.orderBy("JoinDate") \
                   .rowsBetween(Window.unboundedPreceding, Window.currentRow)

# Running Total
result = df.withColumn(
    "RunningSalaryTotal",
    sum("Salary").over(windowSpec)
)

print("Running Total of Salary")
result.show()

"""5.Create two DataFrames (Employees and Departments) and demonstrate the following joins:
Inner Join
Left Join
Right Join
Full Outer Join
Left Semi Join
Left Anti Join
Cross Join
Self Join
"""

from pyspark.sql import SparkSession

# Create Spark Session
spark = SparkSession.builder \
    .appName("JoinExample") \
    .master("local[*]") \
    .getOrCreate()

# Employee DataFrame
emp_data = [
    (101,"Alice",1),
    (102,"Bob",2),
    (103,"Charlie",3),
    (104,"David",2),
    (105,"Eva",4)
]

emp_columns = ["EmpID","Name","DeptID"]

emp_df = spark.createDataFrame(emp_data, emp_columns)

# Department DataFrame
dept_data = [
    (1,"HR"),
    (2,"IT"),
    (3,"Finance"),
    (5,"Marketing")
]

dept_columns = ["DeptID","Department"]

dept_df = spark.createDataFrame(dept_data, dept_columns)

print("Employee DataFrame")
emp_df.show()

print("Department DataFrame")
dept_df.show()

# Inner Join
print("Inner Join")
emp_df.join(dept_df, "DeptID", "inner").show()

# Left Join
print("Left Join")
emp_df.join(dept_df, "DeptID", "left").show()

# Right Join
print("Right Join")
emp_df.join(dept_df, "DeptID", "right").show()

# Full Outer Join
print("Full Outer Join")
emp_df.join(dept_df, "DeptID", "outer").show()

# Left Semi Join
print("Left Semi Join")
emp_df.join(dept_df, "DeptID", "left_semi").show()

# Left Anti Join
print("Left Anti Join")
emp_df.join(dept_df, "DeptID", "left_anti").show()

# Cross Join
print("Cross Join")
emp_df.crossJoin(dept_df).show()

from pyspark.sql.functions import col

# Self Join
print("Self Join")

emp1 = emp_df.alias("emp1")
emp2 = emp_df.alias("emp2")

self_join = emp1.join(
    emp2,
    col("emp1.DeptID") == col("emp2.DeptID"),
    "inner"
).select(
    col("emp1.Name").alias("Employee1"),
    col("emp2.Name").alias("Employee2"),
    col("emp1.DeptID").alias("DeptID")
)

self_join.show()