# -*- coding: utf-8 -*-
"""SCD using PySpark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y33V-L-zY2AVnItIAWnCeEzqRj9qGrOT
"""

!pip install pyspark

from pyspark.sql import SparkSession, functions as F
from pyspark.sql.window import Window

spark = SparkSession.builder.appName("SCD_Assignment").getOrCreate()

baseline_data = [
    (101, "Wireless Mouse", "Electronics", 799, "TechSource"),
    (102, "Office Chair", "Furniture", 4500, "ComfortWorks"),
    (103, "Notebook Set", "Stationery", 150, "PaperPlus"),
    (104, "LED Monitor", "Electronics", 9500, "TechSource"),
    (105, "Standing Desk", "Furniture", 12000, "ComfortWorks"),
    (106, "Backpack", "Accessories", 1200, "UrbanGear"),
    (107, "Water Bottle", "Accessories", 350, "UrbanGear"),
    (108, "Desk Lamp", "Furniture", 899, "ComfortWorks"),
    (109, "Bluetooth Speaker", "Electronics", 2500, "TechSource"),
    (110, "Notebook Cover", "Stationery", 99, "PaperPlus"),
]
columns = ["ProductID", "ProductName", "Category", "Price", "Supplier"]
baseline_df = spark.createDataFrame(baseline_data, columns)

updates_data = [
    (101, "Wireless Mouse", "Electronics", 699, "TechSource"),
    (104, "LED Monitor", "Electronics", 9500, "VisionTech"),
    (106, "Backpack", "Travel", 1200, "UrbanGear"),
    (108, "Desk Lamp", "Furniture", 749, "ComfortWorks"),
]
updates_df = spark.createDataFrame(updates_data, columns)

# SCD Type 1 — left_anti join + unionByName

type1_unchanged = baseline_df.join(updates_df, on="ProductID", how="left_anti")
type1_result = type1_unchanged.unionByName(updates_df).orderBy("ProductID")

print("=== SCD Type 1 result ===")
type1_result.show()

#  SCD Type 2 — three-way union

today = F.current_date()

# Rows that never changed
type2_unchanged = (
    baseline_df.join(updates_df, on="ProductID", how="left_anti")
    .withColumn("StartDate", F.lit("2026-01-01").cast("date"))
    .withColumn("EndDate", F.lit(None).cast("date"))
    .withColumn("IsCurrent", F.lit(1))
)

#  Old versions of changed rows -> now expired
type2_expired = (
    baseline_df.join(updates_df.select("ProductID"), on="ProductID", how="inner")
    .withColumn("StartDate", F.lit("2026-01-01").cast("date"))
    .withColumn("EndDate", today)
    .withColumn("IsCurrent", F.lit(0))
)

# New versions of changed rows -> now current
type2_new = (
    updates_df
    .withColumn("StartDate", today)
    .withColumn("EndDate", F.lit(None).cast("date"))
    .withColumn("IsCurrent", F.lit(1))
)

type2_result = (
    type2_unchanged.unionByName(type2_expired)
    .unionByName(type2_new)
    .orderBy("ProductID", "StartDate")
)

print("=== SCD Type 2 result ===")
type2_result.show()

row_counts = type2_result.groupBy("ProductID").count()
print("Products with 2 rows (changed):", row_counts.filter("count = 2").count())
print("Products with 1 row (unchanged):", row_counts.filter("count = 1").count())

# SCD Type 3 — when/otherwise conditional shift


changed_ids = [101, 104, 106, 108]

joined = baseline_df.alias("old").join(
    updates_df.alias("new"), on="ProductID", how="left"
)

type3_result = joined.select(
    F.col("old.ProductID").alias("ProductID"),
    F.col("old.ProductName").alias("ProductName"),
    F.when(F.col("old.ProductID").isin(changed_ids), F.col("new.Category"))
     .otherwise(F.col("old.Category")).alias("Category"),
    F.when(F.col("old.ProductID").isin(changed_ids), F.col("old.Category"))
     .otherwise(F.lit(None)).alias("PreviousCategory"),
    F.when(F.col("old.ProductID").isin(changed_ids), F.col("new.Price"))
     .otherwise(F.col("old.Price")).alias("Price"),
    F.when(F.col("old.ProductID").isin(changed_ids), F.col("old.Price"))
     .otherwise(F.lit(None)).alias("PreviousPrice"),
    F.when(F.col("old.ProductID").isin(changed_ids), F.col("new.Supplier"))
     .otherwise(F.col("old.Supplier")).alias("Supplier"),
    F.when(F.col("old.ProductID").isin(changed_ids), F.col("old.Supplier"))
     .otherwise(F.lit(None)).alias("PreviousSupplier"),
).orderBy("ProductID")

print("=== SCD Type 3 result ===")
type3_result.show()

earliest_price = (
    type2_result.filter("StartDate = '2026-01-01'")
    .select("ProductID", F.col("Price").alias("StartingPrice"))
)

current_rows = type2_result.filter("IsCurrent = 1")

price_changed_products = (
    current_rows.join(earliest_price, on="ProductID")
    .filter(F.col("Price") != F.col("StartingPrice"))
    .select("ProductID", "ProductName", "StartingPrice", F.col("Price").alias("CurrentPrice"))
)

print("=== Products currently priced differently than at the start ===")
price_changed_products.show()